package cli

import (
	"strings"
	"testing"
)

const genDatabases = `# Generated by ` + "`infrata import`" + `.
resources:
  # imported from db-9
  orders:
    type: fake.database
    engine: postgres
  # imported from db-10
  # TODO: set password — omitted because the provider marks it sensitive
  billing:
    type: fake.database
    engine: mysql
`

// TestMergingIsIdempotent. Re-running import must be safe: it is the command
// people run when they are unsure what happened the first time.
func TestMergingIsIdempotent(t *testing.T) {
	merged, changed := mergeGenerated([]byte(genDatabases), []byte(genDatabases))
	if changed {
		t.Error("merging a file into itself reported a change")
	}
	if string(merged) != genDatabases {
		t.Errorf("merging a file into itself altered it:\n%s", merged)
	}
	// And the resources are not duplicated, which `changed` alone does not
	// prove — a merge that appended everything and reported false would pass
	// the check above only by accident.
	if n := strings.Count(string(merged), "  orders:"); n != 1 {
		t.Errorf("`orders` appears %d times after re-merging", n)
	}
}

// TestMergingAppendsOnlyWhatIsNew — the second import of a growing account adds
// the new resource and leaves the existing ones alone.
func TestMergingAppendsOnlyWhatIsNew(t *testing.T) {
	fresh := `# Generated by ` + "`infrata import`" + `.
resources:
  # imported from db-9
  orders:
    type: fake.database
    engine: postgres
  # imported from db-77
  archive:
    type: fake.database
    engine: postgres
`
	merged, changed := mergeGenerated([]byte(genDatabases), []byte(fresh))
	got := string(merged)
	if !changed {
		t.Fatal("a genuinely new resource reported no change")
	}
	if !strings.Contains(got, "  archive:") {
		t.Errorf("the new resource was not appended:\n%s", got)
	}
	if n := strings.Count(got, "  orders:"); n != 1 {
		t.Errorf("`orders` appears %d times — an existing resource was duplicated:\n%s", n, got)
	}
	// The hand-editable half. A user's edits to an existing block survive,
	// because only unseen names are appended.
	if !strings.Contains(got, "engine: mysql") {
		t.Errorf("an existing resource was rewritten:\n%s", got)
	}
	// The new resource keeps its provenance comment.
	if !strings.Contains(got, "imported from db-77") {
		t.Errorf("the appended block lost its comment:\n%s", got)
	}
}

// TestMergingNeverOverwritesAUserEditedBlock. The point of appending rather
// than rewriting: someone has filled in the password the generator omitted, and
// a second import must not undo that.
func TestMergingNeverOverwritesAUserEditedBlock(t *testing.T) {
	edited := `resources:
  orders:
    type: fake.database
    engine: postgres
    password: ${db_password}
`
	merged, changed := mergeGenerated([]byte(edited), []byte(genDatabases))
	got := string(merged)
	if !strings.Contains(got, "password: ${db_password}") {
		t.Fatalf("a user's edit was lost:\n%s", got)
	}
	if n := strings.Count(got, "  orders:"); n != 1 {
		t.Errorf("`orders` appears %d times:\n%s", n, got)
	}
	// `billing` is genuinely new and must still arrive.
	if !changed || !strings.Contains(got, "  billing:") {
		t.Errorf("the new resource did not arrive alongside the preserved edit:\n%s", got)
	}
}

// TestMergingIntoAnEmptyOrAbsentFileWritesItWhole.
func TestMergingIntoAnEmptyOrAbsentFileWritesItWhole(t *testing.T) {
	for _, existing := range []string{"", "   \n\n"} {
		merged, changed := mergeGenerated([]byte(existing), []byte(genDatabases))
		if !changed || string(merged) != genDatabases {
			t.Errorf("merging into %q did not write the file whole:\n%s", existing, merged)
		}
	}
}

// TestResourceKeyRecognisesOnlyResourceKeys. The merge decides what is already
// declared by reading these, so a line it misreads is either a duplicated
// resource or a lost one.
func TestResourceKeyRecognisesOnlyResourceKeys(t *testing.T) {
	for _, tc := range []struct {
		line string
		want string
	}{
		{"  orders:", "orders"},
		{"  vpc-0a1b:", "vpc-0a1b"},
		{"  _0abc:", "_0abc"},
		// Not resource keys: wrong indentation, a value, a comment, a top-level
		// key, an attribute.
		{"resources:", ""},
		{"    engine: postgres", ""},
		{"    type: fake.database", ""},
		{"  # imported from db-9", ""},
		{"      nested:", ""},
		{"  0bad:", ""},
		{"  has space:", ""},
		{"", ""},
	} {
		got, ok := resourceKey(tc.line)
		if tc.want == "" {
			if ok {
				t.Errorf("resourceKey(%q) = %q, want it rejected", tc.line, got)
			}
			continue
		}
		if !ok || got != tc.want {
			t.Errorf("resourceKey(%q) = %q, %v; want %q, true", tc.line, got, ok, tc.want)
		}
	}
}
