package cli

import (
	"strings"
	"testing"

	"github.com/infrena/infrena/internal/discovery"
	"github.com/infrena/infrena/internal/state"
	"github.com/infrena/infrena/pkg/address"
	"github.com/infrena/infrena/pkg/resource"
)

const genDatabases = `# Generated by ` + "`infrena import`" + `.
resources:
  # imported from db-9
  orders:
    type: fake.database
    engine: postgres
  # imported from db-10
  # TODO: set password — omitted because the provider marks it sensitive
  billing:
    type: fake.database
    engine: mysql
`

// TestMergingIsIdempotent. Re-running import must be safe: it is the command
// people run when they are unsure what happened the first time.
func TestMergingIsIdempotent(t *testing.T) {
	merged, changed := mergeGenerated([]byte(genDatabases), []byte(genDatabases))
	if changed {
		t.Error("merging a file into itself reported a change")
	}
	if string(merged) != genDatabases {
		t.Errorf("merging a file into itself altered it:\n%s", merged)
	}
	// And the resources are not duplicated, which `changed` alone does not
	// prove — a merge that appended everything and reported false would pass
	// the check above only by accident.
	if n := strings.Count(string(merged), "  orders:"); n != 1 {
		t.Errorf("`orders` appears %d times after re-merging", n)
	}
}

// TestMergingAppendsOnlyWhatIsNew — the second import of a growing account adds
// the new resource and leaves the existing ones alone.
func TestMergingAppendsOnlyWhatIsNew(t *testing.T) {
	fresh := `# Generated by ` + "`infrena import`" + `.
resources:
  # imported from db-9
  orders:
    type: fake.database
    engine: postgres
  # imported from db-77
  archive:
    type: fake.database
    engine: postgres
`
	merged, changed := mergeGenerated([]byte(genDatabases), []byte(fresh))
	got := string(merged)
	if !changed {
		t.Fatal("a genuinely new resource reported no change")
	}
	if !strings.Contains(got, "  archive:") {
		t.Errorf("the new resource was not appended:\n%s", got)
	}
	if n := strings.Count(got, "  orders:"); n != 1 {
		t.Errorf("`orders` appears %d times — an existing resource was duplicated:\n%s", n, got)
	}
	// The hand-editable half. A user's edits to an existing block survive,
	// because only unseen names are appended.
	if !strings.Contains(got, "engine: mysql") {
		t.Errorf("an existing resource was rewritten:\n%s", got)
	}
	// The new resource keeps its provenance comment.
	if !strings.Contains(got, "imported from db-77") {
		t.Errorf("the appended block lost its comment:\n%s", got)
	}
}

// TestMergingNeverOverwritesAUserEditedBlock. The point of appending rather
// than rewriting: someone has filled in the password the generator omitted, and
// a second import must not undo that.
func TestMergingNeverOverwritesAUserEditedBlock(t *testing.T) {
	edited := `resources:
  orders:
    type: fake.database
    engine: postgres
    password: ${db_password}
`
	merged, changed := mergeGenerated([]byte(edited), []byte(genDatabases))
	got := string(merged)
	if !strings.Contains(got, "password: ${db_password}") {
		t.Fatalf("a user's edit was lost:\n%s", got)
	}
	if n := strings.Count(got, "  orders:"); n != 1 {
		t.Errorf("`orders` appears %d times:\n%s", n, got)
	}
	// `billing` is genuinely new and must still arrive.
	if !changed || !strings.Contains(got, "  billing:") {
		t.Errorf("the new resource did not arrive alongside the preserved edit:\n%s", got)
	}
}

// TestMergingIntoAnEmptyOrAbsentFileWritesItWhole.
func TestMergingIntoAnEmptyOrAbsentFileWritesItWhole(t *testing.T) {
	for _, existing := range []string{"", "   \n\n"} {
		merged, changed := mergeGenerated([]byte(existing), []byte(genDatabases))
		if !changed || string(merged) != genDatabases {
			t.Errorf("merging into %q did not write the file whole:\n%s", existing, merged)
		}
	}
}

// TestResourceKeyRecognisesOnlyResourceKeys. The merge decides what is already
// declared by reading these, so a line it misreads is either a duplicated
// resource or a lost one.
func TestResourceKeyRecognisesOnlyResourceKeys(t *testing.T) {
	for _, tc := range []struct {
		line string
		want string
	}{
		{"  orders:", "orders"},
		{"  vpc-0a1b:", "vpc-0a1b"},
		{"  _0abc:", "_0abc"},
		// Not resource keys: wrong indentation, a value, a comment, a top-level
		// key, an attribute.
		{"resources:", ""},
		{"    engine: postgres", ""},
		{"    type: fake.database", ""},
		{"  # imported from db-9", ""},
		{"      nested:", ""},
		{"  0bad:", ""},
		{"  has space:", ""},
		{"", ""},
	} {
		got, ok := resourceKey(tc.line)
		if tc.want == "" {
			if ok {
				t.Errorf("resourceKey(%q) = %q, want it rejected", tc.line, got)
			}
			continue
		}
		if !ok || got != tc.want {
			t.Errorf("resourceKey(%q) = %q, %v; want %q, true", tc.line, got, ok, tc.want)
		}
	}
}

// stateWith builds a state holding one managed resource.
func stateWith(name, typ, instance, providerID string) *state.State {
	st := state.New("proj", "dev")
	st.Set(&resource.ResourceState{
		Address:    address.Address{Name: name},
		Type:       typ,
		Provider:   instance,
		ProviderID: providerID,
	})
	return st
}

// TestAnIDManagedInAnotherAccountIsNotACollision.
//
// `alreadyManaged` keys its claims by type AND INSTANCE, not by provider ID alone,
// and this is the only thing asserting it. Established by measurement: collapsing
// the key to (type, id) broke NOTHING in the whole suite — including the integration
// test for the duplicate-import bug this guard exists to stop, which uses one
// instance and so cannot tell the two keyings apart.
//
// What the missing axis would cost is an over-refusal, which is the failure mode a
// guard is most likely to be trusted through: a provider ID is unique within an
// ACCOUNT, not across them (§12.1), so two instances of one plugin legitimately
// hold the same ID — `net-1` in each cloud file of the fake provider, and in AWS
// any pair of accounts. Keyed globally, adopting a resource into a second account
// would be refused because an unrelated account already manages that ID, and the
// message would name an address that has nothing to do with it.
func TestAnIDManagedInAnotherAccountIsNotACollision(t *testing.T) {
	// `main` manages net-1. acct2's net-1 is a DIFFERENT resource, unmanaged.
	st := stateWith("net", "fake.network", "main", "net-1")
	selected := []discovery.Result{
		{Name: "adopted", Type: "fake.network", Provider: "acct2", ProviderID: "net-1"},
	}

	if got := alreadyManaged(st, selected); len(got) != 0 {
		t.Errorf("refused an import into a different account: %v\n"+
			"a provider ID is unique within an account, not across them", got)
	}

	// The control, in the same test so neither direction can pass alone: the same
	// ID in the SAME instance is the collision, and it names the address holding it.
	same := []discovery.Result{
		{Name: "adopted", Type: "fake.network", Provider: "main", ProviderID: "net-1"},
	}
	got := alreadyManaged(st, same)
	if len(got) != 1 {
		t.Fatalf("the real collision was not reported: %v", got)
	}
	if !strings.Contains(got[0], "net-1") || !strings.Contains(got[0], "net") {
		t.Errorf("the report names neither the ID nor its owner: %q", got[0])
	}
}

// TestImportingUnderTheSameNameIsLeftToTheNameCheck.
//
// The two guards must not both fire for one mistake. Re-importing the same resource
// at the same address is the name collision, whose message is about overwriting what
// is recorded — a different and more accurate thing to say than "two addresses would
// manage one resource", which is not what would happen.
func TestImportingUnderTheSameNameIsLeftToTheNameCheck(t *testing.T) {
	st := stateWith("net", "fake.network", "main", "net-1")
	selected := []discovery.Result{
		{Name: "net", Type: "fake.network", Provider: "main", ProviderID: "net-1"},
	}
	if got := alreadyManaged(st, selected); len(got) != 0 {
		t.Errorf("the provider-ID guard fired on a plain name collision: %v", got)
	}
}

// TestAnEntryWithNoProviderIDClaimsNothing.
//
// An empty provider ID names no real resource, so it cannot be the thing being
// adopted twice. Without the skip, every such entry would claim the ID "" and the
// first import of anything unmanaged would be refused by it.
func TestAnEntryWithNoProviderIDClaimsNothing(t *testing.T) {
	st := stateWith("placeholder", "fake.network", "main", "")
	selected := []discovery.Result{
		{Name: "adopted", Type: "fake.network", Provider: "main", ProviderID: ""},
	}
	if got := alreadyManaged(st, selected); len(got) != 0 {
		t.Errorf("an entry with no provider ID was treated as managing something: %v", got)
	}
}

// TestAnAmbiguousSelectorIsRefusedRatherThanResolvedArbitrarily.
//
// A selector is `<type>.<provider id>`, which names no instance — and a provider ID is
// unique within an ACCOUNT, not across them (§12.1), so two instances of one plugin can
// each hold `net-1`. `byID` was a plain map keyed by type and ID, so the second
// candidate overwrote the first and one account won by map-insertion order. The loser
// was not reported: the user asked to adopt a resource, got a different one, and
// nothing in the output said so.
//
// Refusing is the only correct answer with this syntax, and the refusal has to name
// both candidates and their instances, or the user cannot tell which is which — the
// action is --provider.
func TestAnAmbiguousSelectorIsRefusedRatherThanResolvedArbitrarily(t *testing.T) {
	found := []discovery.Result{
		{Name: "net", Type: "fake.network", Provider: "main", ProviderID: "net-1"},
		{Name: "net", Type: "fake.network", Provider: "acct2", ProviderID: "net-1"},
	}

	_, err := narrowToSelectors(found, []string{"fake.network.net-1"}, "")
	if err == nil {
		t.Fatal("two accounts hold net-1; picking one silently adopts a resource the user did not name")
	}
	for _, want := range []string{"fake.network.net-1", "main", "acct2", "--provider"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the refusal omits %q, so the user cannot act on it:\n%v", want, err)
		}
	}
}

// TestProviderNarrowsAnOtherwiseAmbiguousSelector is the way out the message names.
// Without this the refusal above would be a dead end, which §44 forbids: a suggested
// action has to be one the reader can take.
func TestProviderNarrowsAnOtherwiseAmbiguousSelector(t *testing.T) {
	found := []discovery.Result{
		{Name: "net", Type: "fake.network", Provider: "main", ProviderID: "net-1"},
		{Name: "net", Type: "fake.network", Provider: "acct2", ProviderID: "net-1"},
	}

	got, err := narrowToSelectors(found, []string{"fake.network.net-1"}, "acct2")
	if err != nil {
		t.Fatalf("--provider acct2 must resolve the ambiguity: %v", err)
	}
	if len(got) != 1 || got[0].Provider != "acct2" {
		t.Fatalf("selected %+v, want the acct2 candidate alone", got)
	}
}

// TestAnUnambiguousSelectorStillWorksWithoutProvider.
//
// The control. A check that refused whenever two results shared a type would pass the
// two tests above and break every ordinary import, and one instance is the common case.
func TestAnUnambiguousSelectorStillWorksWithoutProvider(t *testing.T) {
	found := []discovery.Result{
		{Name: "net", Type: "fake.network", Provider: "main", ProviderID: "net-1"},
		{Name: "other", Type: "fake.network", Provider: "main", ProviderID: "net-2"},
	}

	got, err := narrowToSelectors(found, []string{"fake.network.net-2"}, "")
	if err != nil {
		t.Fatalf("net-2 is held by exactly one instance: %v", err)
	}
	if len(got) != 1 || got[0].ProviderID != "net-2" {
		t.Fatalf("selected %+v, want net-2 alone", got)
	}
}

// TestProviderNamingNoInstanceIsRefused.
//
// A typo in --provider must not silently import nothing: with no selectors, import
// adopts everything discovery found, so an unmatched instance name would quietly become
// "import nothing" and report success.
func TestProviderNamingNoInstanceIsRefused(t *testing.T) {
	found := []discovery.Result{
		{Name: "net", Type: "fake.network", Provider: "main", ProviderID: "net-1"},
	}

	if _, err := narrowToSelectors(found, nil, "acct3"); err == nil {
		t.Error("--provider naming an instance that holds nothing must be refused, not treated as an empty import")
	}
}
