// Package generator renders discovered resources as minimal YAML (spec §27).
//
// Minimal means: emit what the user must know, and nothing they would have got
// anyway. A `test.database` with six attributes of which five equal their
// provider default is one line of configuration, because five of those lines
// would be noise a reader has to check against the schema to dismiss.
//
// THIS PACKAGE IS THE ONE ARGUED EXCEPTION to "internal/config is the only
// package permitted to touch yaml.Node" (spec §7, M8 Global Constraints). It
// EMITS YAML and never parses any: the hazard that rule protects against is two
// packages interpreting a document differently, and nothing here interprets
// anything. yaml.Node rather than yaml.Marshal is required because generated
// configuration carries COMMENTS — an omitted secret that says nothing reads as
// a resource with no password, rather than as one whose password the reader
// must supply.
package generator

import (
	"bytes"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/infrata/infrata/internal/registry"
	"github.com/infrata/infrata/pkg/schema"
	"github.com/infrata/infrata/pkg/value"
)

// Resource is one thing to write out: the name it will be known by in
// configuration (internal/discovery decided that) and what the provider
// reported about it.
type Resource struct {
	Name       string
	Type       string
	ProviderID string
	// Provider is the instance this resource belongs to, which is what selects the
	// `defaults:` block Minimal measures against (PLAN.md §12.1).
	Provider   string
	Attributes map[string]value.Value
}

// File is one generated file: the name it should be written under, relative to
// `discovered/`, and its contents.
type File struct {
	Name  string
	Bytes []byte
}

// Options selects how much is written.
type Options struct {
	// Minimal omits an attribute whose value equals what the provider default
	// would have supplied anyway (spec §27). `import --generate` sets it;
	// `export` does not, because §28's job is the opposite — a full record for
	// auditing and migration, where a value that happens to match today's
	// default is still a fact about the resource.
	//
	// It does NOT govern the other two omissions. A computed attribute stays
	// out of both, because configuration may not set one at all; and a
	// sensitive attribute stays out of both, because §28 carries the same
	// sensitivity rule as §27 and an audit dump is, if anything, more likely to
	// be pasted somewhere public.
	Minimal bool

	// Header is the comment block written at the top of each file. Empty means
	// none.
	Header string

	// InstanceDefaults is each provider instance's `defaults:` block, keyed by
	// instance name.
	//
	// Minimal omits a value equal to one of these for exactly the reason it omits a
	// schema default: it is not something the reader has to supply, and a generated
	// file that restates it is a file whose next diff is noise. Nil is the ordinary
	// case — a project declaring no `defaults:` — and omits nothing extra.
	InstanceDefaults map[string]map[string]value.Value
}

// MinimalOptions is what `import --generate` uses.
func MinimalOptions() Options {
	return Options{
		Minimal: true,
		Header: "Generated by `infrata import`. Edit freely — this file is loaded like any\n" +
			"other, and is the configuration that keeps imported resources from being\n" +
			"destroyed on the next apply.",
	}
}

// Generate renders resources into one file per resource type (§27.1: "logical
// file names, like databases.yml").
//
// Files and the resources inside them are sorted. Generated configuration is
// read in diffs — a file whose lines reorder between two runs against unchanged
// infrastructure is a file nobody can review.
func Generate(resources []Resource, reg *registry.Registry, ctx schema.DefaultContext, opts Options) ([]File, error) {
	grouped := map[string][]Resource{}
	for _, r := range resources {
		name := FileName(r.Type)
		grouped[name] = append(grouped[name], r)
	}

	names := make([]string, 0, len(grouped))
	for name := range grouped {
		names = append(names, name)
	}
	sort.Strings(names)

	out := make([]File, 0, len(names))
	for _, name := range names {
		b, err := renderFile(grouped[name], reg, ctx, opts)
		if err != nil {
			return nil, err
		}
		out = append(out, File{Name: name, Bytes: b})
	}
	return out, nil
}

// renderFile writes one `resources:` document.
func renderFile(resources []Resource, reg *registry.Registry, ctx schema.DefaultContext, opts Options) ([]byte, error) {
	sorted := append([]Resource(nil), resources...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	body := &yaml.Node{Kind: yaml.MappingNode}
	for _, r := range sorted {
		key := &yaml.Node{Kind: yaml.ScalarNode, Value: r.Name}
		if r.ProviderID != "" {
			// The provider ID is the only thing connecting generated
			// configuration back to the resource it describes, and it is NOT
			// an attribute — state holds it. A comment is where it can be said
			// without becoming something the compiler has to reject.
			key.HeadComment = "imported from " + r.ProviderID
		}
		node, notes, err := renderResource(r, reg, ctx, opts)
		if err != nil {
			return nil, err
		}
		for _, n := range notes {
			if key.HeadComment != "" {
				key.HeadComment += "\n"
			}
			key.HeadComment += n
		}
		body.Content = append(body.Content, key, node)
	}

	doc := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{
		{Kind: yaml.ScalarNode, Value: "resources"},
		body,
	}}

	var buf bytes.Buffer
	for _, line := range strings.Split(opts.Header, "\n") {
		if opts.Header == "" {
			break
		}
		buf.WriteString("# " + line + "\n")
	}
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// renderResource emits one resource, omitting everything a reader would not
// have to write themselves.
//
// Three kinds of omission, and they are not interchangeable:
//
//   - COMPUTED attributes are omitted because configuration may not set them at
//     all. `id` and `endpoint` come back from every discovery, and emitting one
//     produces "is computed and cannot be set" — generated configuration that
//     does not load, with a diagnostic pointing at a file nobody wrote.
//   - SENSITIVE attributes are omitted because a generated file is destined for
//     version control, and a secret committed to git is a secret ROTATED, not a
//     secret deleted. This is the milestone's sharpest hazard.
//   - Attributes EQUAL TO THEIR DEFAULT are omitted because §27 says minimal.
//     This one is a nicety; the first two are correctness.
//
// The first two say so in a comment. A silent omission tells a reader the
// resource has no password, rather than that they must supply one.
func renderResource(r Resource, reg *registry.Registry, ctx schema.DefaultContext, opts Options) (*yaml.Node, []string, error) {
	def, known := reg.Definition(r.Type)

	node := &yaml.Node{Kind: yaml.MappingNode}
	typeVal := &yaml.Node{Kind: yaml.ScalarNode, Value: r.Type}
	node.Content = append(node.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "type"}, typeVal)

	var notes []string
	if !known {
		// A type the registry does not know cannot be filtered against a
		// schema, so nothing is omitted and the file says why. Emitting
		// nothing would silently lose the resource.
		notes = append(notes, "WARNING: "+r.Type+" is unknown to this build; nothing below was filtered")
	}

	// Sorted: Go's map iteration is randomised, and these lines are read in
	// diffs.
	attrNames := make([]string, 0, len(r.Attributes))
	for name := range r.Attributes {
		attrNames = append(attrNames, name)
	}
	sort.Strings(attrNames)

	var omittedSecrets []string
	for _, name := range attrNames {
		v := r.Attributes[name]
		if !v.Known {
			continue
		}

		if known {
			attr, declared := def.Attribute(name)
			if !declared {
				// The provider reported something its own schema does not
				// declare. Emitting it produces "no such attribute"; the
				// resource is still worth writing without it.
				continue
			}
			if attr.Computed {
				continue
			}
			if attr.Sensitive {
				omittedSecrets = append(omittedSecrets, name)
				continue
			}
			if opts.Minimal && equalsDefault(attr, v, ctx) {
				continue
			}
			// The INSTANCE's default, which outranks the schema's (§12.1) and is
			// just as much not the reader's job to write down.
			if opts.Minimal && equalsInstanceDefault(opts, r.Provider, name, v) {
				continue
			}
		}

		// Converted to plain Go data first. v.Raw for a composite is
		// map[string]value.Value, and encoding THAT writes the internal struct
		// — kind, known, source, sensitive, and the secret in clear. An export
		// did exactly that until M10's integration test caught it.
		plain, hidden, keep := plainValue(v)
		omittedSecrets = append(omittedSecrets, prefixed(name, hidden)...)
		if !keep {
			continue
		}
		scalar := &yaml.Node{}
		if err := scalar.Encode(plain); err != nil {
			return nil, nil, fmt.Errorf("rendering %s.%s: %w", r.Name, name, err)
		}
		node.Content = append(node.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: name}, scalar)
	}

	if len(omittedSecrets) > 0 {
		// On the RESOURCE rather than on an attribute line, because the
		// attribute it is about is the one thing not in the file. A resource
		// whose every other attribute was omitted still carries this.
		// The wording differs by mode because the reader's job differs. A
		// generated file is configuration they must complete; an export is a
		// record they are reading. "TODO: set this" in an audit dump reads as
		// an instruction to edit a file nobody is going to apply.
		if opts.Minimal {
			notes = append(notes, "TODO: set "+strings.Join(omittedSecrets, ", ")+
				" — omitted because the provider marks "+
				plural(len(omittedSecrets), "it", "them")+" sensitive, and this file is "+
				"destined for version control")
		} else {
			notes = append(notes, "omitted: "+strings.Join(omittedSecrets, ", ")+
				" ("+plural(len(omittedSecrets), "marked", "marked")+" sensitive by the provider)")
		}
	}
	return node, notes, nil
}

// equalsInstanceDefault reports whether v is exactly what the resource's provider
// instance would have supplied through `defaults:`.
//
// Keyed by the resource's OWN instance, never by "any instance that defaults this
// name": two instances of one plugin exist precisely because they differ, and omitting
// a value because the OTHER account happens to default it to that would write a file
// that plans a change the moment it is read back.
func equalsInstanceDefault(opts Options, instance, name string, v value.Value) bool {
	if instance == "" {
		return false
	}
	d, ok := opts.InstanceDefaults[instance][name]
	if !ok {
		return false
	}
	return v.Equal(d)
}

// equalsDefault reports whether v is exactly what this attribute would have
// been given anyway.
//
// It uses the SAME schema.DefaultContext the compiler uses. A default may
// depend on the environment — test.database's size is 100 in production and 10
// elsewhere — so comparing against a zero context would emit `size: 100` for a
// production import (noise) and omit it for a development one (wrong).
func equalsDefault(attr schema.Attribute, v value.Value, ctx schema.DefaultContext) bool {
	if attr.Default == nil {
		return false
	}
	raw, ok := attr.Default(ctx)
	if !ok {
		return false
	}
	def, ok := schema.DatumValue(raw, attr.Kind)
	if !ok {
		// A malformed default is a provider bug. The compiler reports it; here
		// it simply means nothing can be compared, so the value is emitted
		// rather than silently dropped.
		return false
	}
	coerced, ok := value.Coerce(v, attr.Kind)
	if !ok {
		return false
	}
	return coerced.Equal(def)
}

// FileName is the file a resource type is written to: the last segment of the
// type, pluralised. `test.database` -> `databases.yml`.
//
// Grouping by type rather than one file per resource, because an account with
// four hundred resources should not produce four hundred files; and by type
// rather than one big file, because §27.1 asks for logical names a person can
// navigate.
func FileName(resourceType string) string {
	base := resourceType
	if i := strings.LastIndex(resourceType, "."); i >= 0 && i+1 < len(resourceType) {
		base = resourceType[i+1:]
	}
	if base == "" {
		return "resources.yml"
	}
	return pluralise(base) + ".yml"
}

// pluralise handles the shapes a resource type actually takes. It is
// deliberately small: these are file names, and a wrong one is untidy rather
// than broken — unlike a wrong resource name, which is an address.
func pluralise(s string) string {
	switch {
	case strings.HasSuffix(s, "s"), strings.HasSuffix(s, "x"), strings.HasSuffix(s, "z"),
		strings.HasSuffix(s, "ch"), strings.HasSuffix(s, "sh"):
		return s + "es"
	case len(s) > 1 && strings.HasSuffix(s, "y") && !isVowel(s[len(s)-2]):
		return s[:len(s)-1] + "ies"
	default:
		return s + "s"
	}
}

func isVowel(b byte) bool { return strings.IndexByte("aeiou", b) >= 0 }

func plural(n int, one, many string) string {
	if n == 1 {
		return one
	}
	return many
}

// plainValue converts a Value into plain Go data for YAML encoding, omitting
// every SENSITIVE leaf and naming what it omitted.
//
// Two things make this necessary rather than a convenience.
//
// A composite's Raw is map[string]value.Value or []value.Value, so encoding it
// directly writes the ENGINE'S STRUCT — kind, known, source, sensitive, origin,
// and the value itself. An export did precisely that, printing a secret in clear
// beside the flag saying it was secret, until M10's integration test caught it.
//
// And sensitivity is PER LEAF. renderResource checks the schema, which classifies
// an ATTRIBUTE; a leaf inside an unclassified map can still be a secret, because
// it came from somewhere that was. Checking only the attribute is how the secret
// got out.
//
// keep is false when nothing survives — a wholly sensitive value, or an unknown
// one, neither of which has anything to write.
func plainValue(v value.Value) (plain any, omitted []string, keep bool) {
	if v.Sensitive {
		return nil, []string{""}, false
	}
	if !v.Known {
		// Nothing to write. Not an omission worth reporting: an unresolved value
		// is not something the reader must supply, it is something the provider
		// will.
		return nil, nil, false
	}

	switch v.Kind {
	case value.KindMap:
		m, ok := v.Raw.(map[string]value.Value)
		if !ok {
			return nil, nil, false
		}
		out := map[string]any{}
		var hidden []string
		// Sorted, because YAML encoding of a Go map is ordered by key but the
		// OMISSION list is user-visible and must not depend on iteration order.
		for _, k := range sortedValueKeys(m) {
			p, h, keep := plainValue(m[k])
			hidden = append(hidden, prefixed(k, h)...)
			if keep {
				out[k] = p
			}
		}
		if len(out) == 0 {
			return nil, hidden, false
		}
		return out, hidden, true

	case value.KindList:
		items, ok := v.Raw.([]value.Value)
		if !ok {
			return nil, nil, false
		}
		var out []any
		var hidden []string
		for i, item := range items {
			p, h, keep := plainValue(item)
			hidden = append(hidden, prefixed(strconv.Itoa(i), h)...)
			if keep {
				out = append(out, p)
			}
		}
		if len(out) == 0 {
			return nil, hidden, false
		}
		return out, hidden, true

	default:
		return v.Raw, nil, true
	}
}

// prefixed qualifies omitted leaf paths with the key they sit under, so a note
// says `tags.password` rather than `password` — which is the difference between
// a reader knowing where to put the value and guessing.
func prefixed(key string, paths []string) []string {
	if len(paths) == 0 {
		return nil
	}
	out := make([]string, 0, len(paths))
	for _, p := range paths {
		if p == "" {
			out = append(out, key)
			continue
		}
		out = append(out, key+"."+p)
	}
	return out
}

func sortedValueKeys(m map[string]value.Value) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
